# ----------- Stage 1: Build the application -----------
# Base image
FROM node:latest AS builder

# Set working directory
WORKDIR /app

# update/upgrade/clean image packages
RUN apt-get update && apt-get upgrade -y && apt-get clean
  
# copy package.json and package-lock.json
COPY package.json package-lock.json ./

# install only production dependencies and only the ones that exist in package.json
RUN npm i --omit=dev

COPY  . .

RUN npm run build
# ----------- Stage 2: Run the application -----------
FROM node:latest
# Set working directory
WORKDIR /app

# Copy package files and install production deps
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Copy only the compiled output from builder
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node","dist/server.js"]